//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.25 at 09:27:47 上午 CST 
//


package info.u250.spriter.dom;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Key complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Key">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object" type="{}AnimationObject" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="object_ref" type="{}AnimationObjectRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bone_ref" type="{}BoneRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bone" type="{}Bone" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *       &lt;attribute name="spin" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class Key {

    protected List<AnimationObject> object;

    protected List<AnimationObjectRef> objectRef;

    protected List<BoneRef> boneRef;
    protected Bone bone;

    protected Integer id;

    protected Integer time;

    protected Integer spin;

    /**
     * Gets the value of the object property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the object property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnimationObject }
     * 
     * 
     */
    public List<AnimationObject> getObject() {
        if (object == null) {
            object = new ArrayList<AnimationObject>();
        }
        return this.object;
    }

    /**
     * Gets the value of the objectRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnimationObjectRef }
     * 
     * 
     */
    public List<AnimationObjectRef> getObjectRef() {
        if (objectRef == null) {
            objectRef = new ArrayList<AnimationObjectRef>();
        }
        return this.objectRef;
    }

    /**
     * Gets the value of the boneRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the boneRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBoneRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BoneRef }
     * 
     * 
     */
    public List<BoneRef> getBoneRef() {
        if (boneRef == null) {
            boneRef = new ArrayList<BoneRef>();
        }
        return this.boneRef;
    }

    /**
     * Gets the value of the bone property.
     * 
     * @return
     *     possible object is
     *     {@link Bone }
     *     
     */
    public Bone getBone() {
        return bone;
    }

    /**
     * Sets the value of the bone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bone }
     *     
     */
    public void setBone(Bone value) {
        this.bone = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Integer getTime() {
        if (time == null) {
            return  0;
        } else {
            return time;
        }
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTime(Integer value) {
        this.time = value;
    }

    /**
     * Gets the value of the spin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSpin() {
        if (spin == null) {
            return  1;
        } else {
            return spin;
        }
    }

    /**
     * Sets the value of the spin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSpin(Integer value) {
        this.spin = value;
    }

}
